name: basic-action
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
    
      - name: Print
        run: echo "CI TRIGGERED"
